import ast
from typing import Any

from griffe import (
    Class,
    ExprBinOp,
    ExprSubscript,
    Extension,
    Function,
    Inspector,
    ObjectNode,
    Parameter,
    ParameterKind,
    Parameters,
    Visitor,
)


class Pybind11EqNeFix(Extension):
    """Replace pybind11's typed ``__eq__``/``__ne__`` with the canonical ``object`` signature.

    Pybind11 generates overloaded ``__eq__``/``__ne__`` that accept only
    specific types (e.g., ``(self, other: MyClass) -> bool``). Python's
    data model requires these to accept *any* object, so this extension
    replaces them with ``(self, other: object) -> bool`` and drops the
    overloads.
    """

    def on_class_members(
        self,
        *,
        node: ast.AST | ObjectNode,
        cls: Class,
        agent: Visitor | Inspector,
        **kwargs: Any,
    ) -> None:
        for name in ("__eq__", "__ne__"):
            if name not in cls.members:
                continue
            func = cls.members[name]
            if not isinstance(func, Function):
                continue
            func.overloads = []
            func.parameters = Parameters(
                Parameter("self", kind=ParameterKind.positional_or_keyword),
                Parameter("other", kind=ParameterKind.positional_or_keyword, annotation="object"),
            )
            func.returns = "bool"
            func.docstring = None


class Pybind11OptionalCallableFix(Extension):
    """Add ``| None`` to ``Callable`` parameters whose default is ``None``.

    Pybind11 generates signatures like ``callback: Callable[..., None] = None``
    where the annotation must be ``Callable[..., None] | None`` to type-check.
    This extension detects ``Callable[...]`` annotations with a ``None``
    default and wraps them in an ``ExprBinOp`` node, producing the
    structured ``X | None`` form in the rendered stub.
    """

    def on_function_instance(
        self,
        *,
        node: ast.AST | ObjectNode,
        func: Function,
        agent: Visitor | Inspector,
        **kwargs: Any,
    ) -> None:
        self._fix_params(func)
        if func.overloads:
            for overload in func.overloads:
                self._fix_params(overload)

    @staticmethod
    def _fix_params(func: Function) -> None:
        for param in func.parameters:
            if param.annotation is None or param.default is None:
                continue
            if str(param.default) != "None":
                continue
            if not isinstance(param.annotation, ExprSubscript):  # expecting Callable[...]
                continue
            if not str(param.annotation).startswith("collections.abc.Callable"):
                continue
            param.annotation = ExprBinOp(left=param.annotation, operator="|", right="None")


class Pybind11OverloadDedup(Extension):
    """Remove duplicate overload entries generated by pybind11.

    Pybind11 occasionally emits the same overload signature more than once
    (e.g., two identical ``(self, arg0: int) -> bool`` entries). This
    extension deduplicates them by keying on the tuple of stringified
    parameter annotations and return type.
    """

    def on_function_instance(
        self,
        *,
        node: ast.AST | ObjectNode,
        func: Function,
        agent: Visitor | Inspector,
        **kwargs: Any,
    ) -> None:
        if not func.overloads:
            return

        seen: set[tuple[str, ...]] = set()
        deduped: list[Function] = []
        for overload in func.overloads:
            key = (
                *(str(p.annotation) for p in overload.parameters),
                str(overload.returns),
            )
            if key not in seen:
                seen.add(key)
                deduped.append(overload)
        func.overloads = deduped


class Pybind11InPlaceOpFix(Extension):
    """Align in-place operator signatures with their binary counterparts.

    Mypy requires ``__iadd__`` to accept every type that ``__add__`` accepts.
    Pybind11 often generates a narrower signature for the in-place variant
    (e.g., ``__iadd__(self, other: Vector)`` vs ``__add__(self, other: Vector | float)``).
    This extension copies parameter types — and overload structures — from
    the binary operator to the in-place operator.
    """

    _OP_PAIRS = {
        "__iadd__": "__add__",
        "__isub__": "__sub__",
        "__imul__": "__mul__",
        "__itruediv__": "__truediv__",
    }

    def on_class_members(
        self,
        *,
        node: ast.AST | ObjectNode,
        cls: Class,
        agent: Visitor | Inspector,
        **kwargs: Any,
    ) -> None:
        """Copy parameter types from binary operators to their in-place counterparts.

        Also replicates overload structures from ``__add__`` to ``__iadd__``,
        etc., so that mypy sees compatible signatures.
        """
        for iop, op in self._OP_PAIRS.items():
            if iop not in cls.members or op not in cls.members:
                continue
            ifunc = cls.members[iop]
            func = cls.members[op]
            if not isinstance(ifunc, Function) or not isinstance(func, Function):
                continue

            # Copy non-self parameters from __add__ to __iadd__
            op_params = [p for p in func.parameters if p.name != "self"]
            iop_params = [p for p in ifunc.parameters if p.name == "self"]
            iop_params.extend(op_params)
            ifunc.parameters = Parameters(*iop_params)

            # Copy overloads structure if __add__ has overloads
            if func.overloads and not ifunc.overloads:
                ifunc.overloads = []
                for overload in func.overloads:
                    ioverload = Function(name=iop)
                    op_params = [p for p in overload.parameters if p.name != "self"]
                    iop_self = [p for p in ifunc.parameters if p.name == "self"]
                    ioverload.parameters = Parameters(*iop_self, *op_params)
                    ioverload.returns = ifunc.returns
                    ifunc.overloads.append(ioverload)
